import { validarCabecalhos, type ResultadoCabecalhos } from "@integra-correios/validation";

export const TEMPLATE_REMETENTES_HEADERS = [
  "Cartao_postagem",
  "Malote (S ou N)",
  "Codigo",
  "Nome",
  "Email",
  "CPF/CNPJ",
  "Telefone",
  "Celular",
  "CEP",
  "Logradouro",
  "Número",
  "Complemento",
  "Bairro",
  "Cidade",
  "UF",
] as const;

export const TEMPLATE_DESTINATARIOS_HEADERS = [...TEMPLATE_REMETENTES_HEADERS] as const;

export const OBJETO_SIMPLES_HEADERS = [
  "sequencial",
  "codigoServico",
  "codigoServicoAdicional1",
  "codigoServicoAdicional2",
  "codigoServicoAdicional3",
  "codigoServicoAdicional4",
  "codigoServicoAdicional5",
  "valorDeclarado",
  "peso",
  "nomeRemetente",
  "cepRemetente",
  "logradouroRemetente",
  "numeroLogradouroRemetente",
  "complementoRemetente",
  "bairroRemetente",
  "cidadeRemetente",
  "ufRemetente",
  "cnpjRemetente",
  "dddRemetente",
  "telefoneRemetente",
  "emailRemetente",
  "nomeDestinatario",
  "cepDestinatario",
  "logradouroDestinatario",
  "numeroLogradouroDestinatario",
  "complementoDestinatario",
  "bairroDestinatario",
  "cidadeDestinatario",
  "ufDestinatario",
  "cnpjCpfDestinatario",
  "dddDestinatario",
  "telefoneDestinatario",
  "emailDestinatario",
  "dataPrevistaPostagem",
] as const;

export const OBJETO_REGISTRADO_HEADERS = [
  "sequencial",
  "cpfCnpjRemetente",
  "documentoEstrangeiroRemetente",
  "nomeRemetente",
  "dddTelefoneRemetente",
  "telefoneRemetente",
  "dddCelularRemetente",
  "celularRemetente",
  "emailRemetente",
  "observacaoRemetente",
  "cepRemetente",
  "logradouroRemetente",
  "numeroRemetente",
  "complementoRemetente",
  "bairroRemetente",
  "cidadeRemetente",
  "ufRemetente",
  "cpfCnpjDestinatario",
  "documentoEstrangeiroDestinatario",
  "nomeDestinatario",
  "dddTelefoneDestinatario",
  "telefoneDestinatario",
  "dddCelularDestinatario",
  "celularDestinatario",
  "emailDestinatario",
  "observacaoDestinatario",
  "cepDestinatario",
  "logradouroDestinatario",
  "numeroDestinatario",
  "complementoDestinatario",
  "bairroDestinatario",
  "cidadeDestinatario",
  "ufDestinatario",
  "codigoServico",
  "dataPrevistaPostagem",
  "prazoPostagem",
  "logisticaReversa",
  "dataValidadeLogReversa",
  "codigoServicoAdicionalValorDeclarado",
  "valorDeclarado",
  "codigoServicoAdicionalEntregaVizinho",
  "orientacaoEntregaVizinho",
  "codigoServicoAdicional1",
  "codigoServicoAdicional2",
  "codigoServicoAdicional3",
  "pesoInformado",
  "codigoFormatoObjetoInformado",
  "alturaInformada",
  "larguraInformada",
  "comprimentoInformado",
  "diametroInformado",
  "cienteObjetoNaoProibido",
  "observacao",
  "numeroNotaFiscal",
  "chaveNFe",
  "rfidObjeto",
  "DeclaracaoConteudoConteudo1",
  "DeclaracaoConteudoQuantidade1",
  "DeclaracaoConteudoValor1",
  "DeclaracaoConteudoConteudo2",
  "DeclaracaoConteudoQuantidade2",
  "DeclaracaoConteudoValor2",
  "DeclaracaoConteudoConteudo3",
  "DeclaracaoConteudoQuantidade3",
  "DeclaracaoConteudoValor3",
  "DeclaracaoConteudoConteudo4",
  "DeclaracaoConteudoQuantidade4",
  "DeclaracaoConteudoValor4",
  "DeclaracaoConteudoConteudo5",
  "DeclaracaoConteudoQuantidade5",
  "DeclaracaoConteudoValor5",
  "DeclaracaoConteudoConteudo6",
  "DeclaracaoConteudoQuantidade6",
  "DeclaracaoConteudoValor6",
  "DeclaracaoConteudoConteudo7",
  "DeclaracaoConteudoQuantidade7",
  "DeclaracaoConteudoValor7",
  "DeclaracaoConteudoConteudo8",
  "DeclaracaoConteudoQuantidade8",
  "DeclaracaoConteudoValor8",
  "DeclaracaoConteudoConteudo9",
  "DeclaracaoConteudoQuantidade9",
  "DeclaracaoConteudoValor9",
  "DeclaracaoConteudoConteudo10",
  "DeclaracaoConteudoQuantidade10",
  "DeclaracaoConteudoValor10",
  "codigoObjetoIda",
] as const;

export const TIPOS_TEMPLATE = [
  "REMETENTES",
  "DESTINATARIOS",
  "OBJETO_SIMPLES",
  "OBJETO_REGISTRADO",
] as const;

export type TipoTemplate = (typeof TIPOS_TEMPLATE)[number];

const CONTRATOS: Record<TipoTemplate, readonly string[]> = {
  REMETENTES: TEMPLATE_REMETENTES_HEADERS,
  DESTINATARIOS: TEMPLATE_DESTINATARIOS_HEADERS,
  OBJETO_SIMPLES: OBJETO_SIMPLES_HEADERS,
  OBJETO_REGISTRADO: OBJETO_REGISTRADO_HEADERS,
};

export function cabecalhosDoTemplate(tipo: TipoTemplate): readonly string[] {
  return CONTRATOS[tipo];
}

export function validarTemplateOficial(
  tipo: TipoTemplate,
  recebidos: readonly string[],
): ResultadoCabecalhos {
  return validarCabecalhos(recebidos, CONTRATOS[tipo]);
}
